### ISSUE TITLE
Remove Range Error Handling From Frontend 

### ISSUE THREAD

**Issue by Machele-codez** [GMSA-KNUST/QuizApp#1]
The error handling should be handled by the backend API.
All the frontend needs to do is to send the ranges in a request. If they are invalid, the backend responds with an error message to be displayed.

**Comment by labaran1** [comment]
Thinking of it , i think it shouldn't be removed. The validation will reduce load on the server by not sending a request

**Comment by labaran1** [comment]
The front-end validation will provide an instant feedback

**Comment by labaran1** [comment]
we should still include , backend validation, still ensuring the data coming is really valid

**Comment by Machele-codez** [comment]
yeah, but the reason I said that is because the frontend validation is not accurate. Supposing I select Al-Baqarah and Ali-Imran as my range, I should be able to get more than even 20 groups of the shuffled pages, but the frontend would flag that as an invalid range because Ali-Imran is the chapter that comes right after Al-Baqarah.

So we can leave that particular validation to the backend or implement the proper way of handling it instead.

**Comment by labaran1** [comment]
okay i get it now

**Comment by labaran1** [comment]
Implement it on your side , so i will make the changes

**Comment by labaran1** [comment]
Make the api send a bad request code when it encounters an error , rather than 200
