### ISSUE TITLE
Don't show Quran Pages immediately

### ISSUE THREAD

**Issue by Machele-codez** [GMSA-KNUST/QuizApp#4]
The contestant must not see the pages to be recited. 
So after the contestant clicks on one option from the numbered groups, a screen should appear with a button.
Then after the contestant takes a seat, someone else would click the button to display the pages.

**Comment by labaran1** [comment]
ohkay. When the modal is displayed, a show button that display the page

**Comment by Machele-codez** [comment]
> ohkay. When the modal is displayed, a show button that display the page

Yes yes

**Comment by labaran1** [comment]
Should contestant be able to hide the image ??

**Comment by Machele-codez** [comment]
Yes yes, it may come in handy
