### ISSUE TITLE
Modal Shows A Page from Previously Selected Group Before Loading Current Group's Pages

### ISSUE THREAD

**Issue by Machele-codez** [GMSA-KNUST/QuizApp#6]
When I select a certain group and view all 3 pages and then move on to select another group, a page from the previously selected group is displayed until I click next to view the 3 pages of the currently selected group. 

https://user-images.githubusercontent.com/57562100/117473617-ae7f8c00-af49-11eb-92e7-9166d7bd24d5.mp4

Probably, the modal should be cleared after going through all 3 pages of a selected group.

**Comment by labaran1** [comment]
As you can see the selection is still on the 7

**Comment by Machele-codez** [comment]
> As you can see the selection is still on the 7

Oh okay, I see.
